name: Build Plugin - Nightly Version

on: 
  push:
    branches:
      - master
    
jobs:
  checkstyle:
   name: Run checkstyle on plugin
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
     - uses: lix-pm/setup-lix@1.0.0
       with:
         node-version: 12
     - run: lix download
     - run: lix install haxelib:checkstyle
     - run: npm ci
     - run: npm run checkstyle

  build:
    name: Build from publish.hxml using LunaWizard
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: lix-pm/setup-lix@1.0.0
      - run: lix download
      - run: npm ci
      - run: npm run build
      - run: npm run clean:dist
      - name: Archive nightly build
        uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: dist

  publish:
   name: Publish to Itch Nightly Channel
   runs-on: ubuntu-latest
   needs: build
   steps:
    - uses: actions/download-artifact@v2
      with:
        name: nightly
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: nightly
        ITCH_GAME: ${{ github.event.repository.name }}
        ITCH_USER: ${{ github.event.organization.name }}
        PACKAGE: dist
